[project]
site_name = "Megatop documentation"
site_description = "A map-based CMB polarisation experiment data analysis pipeline."
site_author = "Simon Biquard"
site_url = "https://megatop.readthedocs.io/en"
copyright = "Copyright &copy; 2025 SciPol"
repo_url = "https://github.com/CMBSciPol/Megatop"
repo_name = "CMBSciPol/Megatop"

# https://zensical.org/docs/setup/navigation/
nav = [
  { "Home" = "index.md" },
  "science.md",
  { "Getting started" = [
      "getting_started/installation.md",
      "getting_started/tutorial.md"
  ] },
  { "Pipeline steps" = [
      "pipeline/mask.md",
      "pipeline/binning.md",
      "pipeline/mock.md",
      "pipeline/tf.md",
      "pipeline/preprocess.md",
      "pipeline/noise_covariance.md",
      "pipeline/compsep.md",
      "pipeline/map2cl.md",
      "pipeline/noise_spectra.md",
      "pipeline/cl2r.md",
  ] },
  { "API reference" = [
      "api/megatop.md",
      "api/config.md",
      "api/utils.md"
  ] },
]

# https://zensical.org/docs/authoring/math/
extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]

# Enable API reference documentation
# https://zensical.org/docs/setup/extensions/mkdocstrings/
[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]
options.docstring_style = "google"
options.docstring_section_style = "list"
options.show_root_members_full_path = true
options.extensions = ["griffe_fieldz"]  # for attrs

[project.markdown_extensions]
admonition = {}
pymdownx.details = {}
pymdownx.superfences = {}
pymdownx.highlight = { anchor_linenums = true, line_spans = "__span", pygments_lang_class = true }
pymdownx.inlinehilite = {}
pymdownx.snippets = {}
pymdownx.tabbed = { alternate_style = true }
footnotes = {}
pymdownx.caret = {}
pymdownx.keys = {}
pymdownx.mark = {}
pymdownx.tilde = {}
pymdownx.arithmatex = { generic = true }
pymdownx.emoji = {}
abbr = {}
attr_list = {}
def_list = {}
pymdownx.tasklist = { custom_checkbox = true }

[project.theme]
language = "en"
icon.repo = "fontawesome/brands/github"
logo = "megatop_logo.png"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

palette = [
  {
    media = "(prefers-color-scheme)",
    toggle = { icon = "lucide/sun-moon", name = "Switch to light mode" }
  },
  {
    media = "(prefers-color-scheme: light)",
    scheme = "default",
    toggle = { icon = "lucide/sun", name = "Switch to dark mode" }
  },
  {
    media = "(prefers-color-scheme: dark)",
    scheme = "slate",
    toggle = { icon = "lucide/moon", name = "Switch to system preference" }
  },
]
