cl2r_pars:
  dust_marg: false
  lmax_cosmo_analysis: null
  lmin_cosmo_analysis: 50
  load_model_spectra: true
  n_steps: 10000
  n_steps_burnin: 2000
  n_walkers: 200
  prior_bounds:
    A_{dust}:
    - 0.0
    - 1.0
    A_{lens}:
    - 0.0
    - 2.0
    A_{sync}:
    - 0.0
    - 1.0
    r:
    - -0.02
    - 1.0
  sync_marg: false
data_dirs:
  TF_sims_maps: TF_sims_maps
  beams: beams
  maps: maps
  noise_maps: noise_maps
  root: /Users/benjaminberingue/Documents/Research/BB/projects/2403_megatop/planck_test/data
fiducial_cmb:
  lensed_scalar: Cls_Planck2018_lensed_scalar
  unlensed_scalar_tensor_r1: Cls_Planck2018_unlensed_scalar_and_tensor_r1
  root: /Users/benjaminberingue/Documents/Research/BB/projects/2403_megatop/data/fiducial_cmb_spectra
general_pars:
  lmax: 256
  lmin: 30
  nside: 128
map2cl_pars:
  delta_ell: 10
  n_iter_namaster: 3
  purify_b: true
  purify_e: false
map_sets:
- TF_path: .
  exp_tag: SAT4
  file_prefix: ''
  freq_tag: 27
  noise_prefix: noise_
  obsmat_path: .
  simfoTF_prefix: simforTF_
- TF_path: .
  exp_tag: SAT4
  file_prefix: ''
  freq_tag: 39
  noise_prefix: noise_
  obsmat_path: .
  simfoTF_prefix: simforTF_
- TF_path: .
  exp_tag: SAT1
  file_prefix: ''
  freq_tag: 93
  noise_prefix: noise_
  obsmat_path: .
  simfoTF_prefix: simforTF_
- TF_path: .
  exp_tag: SAT1
  file_prefix: ''
  freq_tag: 145
  noise_prefix: noise_
  obsmat_path: .
  simfoTF_prefix: simforTF_
- TF_path: .
  exp_tag: SAT3
  file_prefix: ''
  freq_tag: 225
  noise_prefix: noise_
  obsmat_path: .
  simfoTF_prefix: simforTF_
- TF_path: .
  exp_tag: SAT3
  file_prefix: ''
  freq_tag: 280
  noise_prefix: noise_
  obsmat_path: .
  simfoTF_prefix: simforTF_
map_sim_pars:
  A_lens: 1.0
  TF_n_sim: 1
  TF_power_law_amp: 1.0
  TF_power_law_delta_ell: 1
  TF_power_law_index: -2.0
  cmb_seed: null
  cmb_sim_no_pysm: true
  filter_sims: false
  generate_sims_for_TF: false
  n_sim: 10
  r_input: 0.0
  single_cmb: false
  sky_model:
  - d0
  - s0
masks_pars:
  analysis_mask_name: analysis_mask
  apod_radius: 10.0
  apod_radius_point_source: 4.0
  apod_type: C1
  binary_mask_name: binary_mask
  binary_mask_zero_threshold: 0.1
  gal_key: null
  galactic_mask_name: galactic_mask
  include_galactic: false
  include_sources: false
  input_nhits_map: null
  input_sources_mask: null
  mock_nsources: 100
  mock_sources_hole_radius: 4.0
  nhits_map_name: nhits_map
  sources_mask_name: sources_mask
noise_cov_pars:
  save_preprocessed_noise_maps: true
noise_sim_pars:
  SAC_yrs_LF: 1
  experiment: SO
  include_nhits: true
  n_sim: 10
  noise_option: noise_spectra
  v3_one_over_f_mode: OPTIMISTIC
  v3_sensitivity_mode: GOAL
output_dirs:
  binning: binning
  components: components
  covar: covar
  masks: masks
  mcmc: mcmc
  noise_spectra: noise_spectra
  plots: plots
  preproc: preproc
  root: /Users/benjaminberingue/Documents/Research/BB/projects/2403_megatop/planck_test/output
  spectra: spectra
  transfer_functions: transfer_functions
parametric_sep_pars:
  alm2map: false
  harmonic_delta_ell: 10
  harmonic_lmax: 256
  harmonic_lmin: 30
  include_synchrotron: true
  minimize_method: TNC
  minimize_options:
    disp: false
    eps: 1.0e-12
    ftol: 1.0e-12
    gtol: 1.0e-12
    maxiter: 100
  minimize_tol: 1.0e-18
  use_harmonic_compsep: false
plot_pars:
  lmax_plot: 1000
  lmin_plot: 30
pre_proc_pars:
  beam_fwhms: null
  common_beam_correction: 0.
  correct_for_TF: false
  sum_TF_column: false
