#!/bin/bash

paramfile='/home/jost/code/Megatop/paramfiles/idark_minimal_test.yml'

echo "Running pipeline with paramfile: ${paramfile}"

echo "------------------------------------------------------------"
echo "|           PREPARING METADATA AND SIMULATIONS             |"
echo "------------------------------------------------------------"

echo "Pre-processing data..."
echo "-------------------"

conda init bash
source ~/.bashrc
conda activate megatop


echo "------------------------------------------------------------"
echo "|                       MASK-HANDLING                      |"
echo "------------------------------------------------------------"
megatop-mask-run --globals ${paramfile} 
megatop-mask-plot --globals ${paramfile} 


echo "------------------------------------------------------------"
echo "|                        ON FLY Sims                       |"
echo "------------------------------------------------------------"
megatop-mock-run --globals ${paramfile} 
megatop-mock-run --globals ${paramfile} --noise_only
megatop-mock-plot --globals ${paramfile} 

echo "------------------------------------------------------------"
echo "|                       PRE-PROCESSING                     |"
echo "------------------------------------------------------------"
megatop-preproc-run --globals ${paramfile} 
megatop-preproc-plot --globals ${paramfile} 

echo "------------------------------------------------------------"
echo "|                NOISE-COVARIANCE COMPUTATION              |"
echo "------------------------------------------------------------"
megatop-noisecov-run --globals ${paramfile}
megatop-noisecov-plot --globals ${paramfile}


echo "------------------------------------------------------------"
echo "|                    COMPONENT SEPARATION                  |"
echo "------------------------------------------------------------"
megatop-compsep --globals ${paramfile}


echo "------------------------------------------------------------"
echo "|                     SPECTRA ESTIMATION                   |"
echo "------------------------------------------------------------"
megatop-map2cl --globals ${paramfile}
megatop-spectra-plot --globals ${paramfile}

echo "------------------------------------------------------------"
echo "|                  NOISE SPECTRA ESTIMATION                |"
echo "------------------------------------------------------------"
python noise_spectra_estimator.py --globals ${paramfile}

# python map_to_cl.py --globals ${paramfile} --verbose --plots

# python plot_spectra.py --globals ${paramfile} --plots --verbose
